import Foundation

public struct Budget: Identifiable, Sendable, Equatable {
    public let id: UUID
    public var month: Date
    public var lines: [BudgetLine]
    public var isAutoGenerated: Bool
    public var isAccepted: Bool
    public var createdAt: Date

    public init(
        id: UUID = UUID(),
        month: Date,
        lines: [BudgetLine] = [],
        isAutoGenerated: Bool = false,
        isAccepted: Bool = false,
        createdAt: Date = Date()
    ) {
        self.id = id
        self.month = month
        self.lines = lines
        self.isAutoGenerated = isAutoGenerated
        self.isAccepted = isAccepted
        self.createdAt = createdAt
    }

    public var totalAllocated: Decimal {
        lines.reduce(0) { $0 + $1.allocatedAmount }
    }

    public var totalSpent: Decimal {
        lines.reduce(0) { $0 + $1.spentAmount }
    }

    public var remainingBudget: Decimal {
        totalAllocated - totalSpent
    }
}

public struct BudgetLine: Identifiable, Sendable, Equatable {
    public let id: UUID
    public var categoryId: UUID
    public var allocatedAmount: Decimal
    public var spentAmount: Decimal

    public init(
        id: UUID = UUID(),
        categoryId: UUID,
        allocatedAmount: Decimal,
        spentAmount: Decimal = 0
    ) {
        self.id = id
        self.categoryId = categoryId
        self.allocatedAmount = allocatedAmount
        self.spentAmount = spentAmount
    }

    public var percentUsed: Double {
        guard allocatedAmount > 0 else { return 0 }
        return NSDecimalNumber(decimal: spentAmount / allocatedAmount).doubleValue
    }

    public var isOverBudget: Bool { spentAmount > allocatedAmount }
    public var isNearLimit: Bool { percentUsed >= 0.8 && !isOverBudget }
}
