import Foundation
import SwiftData
import HFDomain

@Model
public final class SDBudget {
    @Attribute(.unique) public var id: UUID
    public var month: Date
    public var isAutoGenerated: Bool
    public var isAccepted: Bool
    public var createdAt: Date

    @Relationship(deleteRule: .cascade, inverse: \SDBudgetLine.budget)
    public var lines: [SDBudgetLine] = []

    public init(from domain: Budget) {
        self.id = domain.id
        self.month = domain.month
        self.isAutoGenerated = domain.isAutoGenerated
        self.isAccepted = domain.isAccepted
        self.createdAt = domain.createdAt
    }

    public func toDomain() -> Budget {
        Budget(
            id: id,
            month: month,
            lines: lines.map { $0.toDomain() },
            isAutoGenerated: isAutoGenerated,
            isAccepted: isAccepted,
            createdAt: createdAt
        )
    }
}

@Model
public final class SDBudgetLine {
    @Attribute(.unique) public var id: UUID
    public var categoryId: UUID
    public var allocatedAmount: Decimal
    public var spentAmount: Decimal

    public var budget: SDBudget?

    public init(from domain: BudgetLine) {
        self.id = domain.id
        self.categoryId = domain.categoryId
        self.allocatedAmount = domain.allocatedAmount
        self.spentAmount = domain.spentAmount
    }

    public func toDomain() -> BudgetLine {
        BudgetLine(
            id: id,
            categoryId: categoryId,
            allocatedAmount: allocatedAmount,
            spentAmount: spentAmount
        )
    }
}
